# Generated by Django 2.2.6 on 2019-10-28 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default_dinner.jpg', upload_to='media/recipe_pics')),
                ('recipe', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('cuisine', models.CharField(choices=[('African', 'AFRICAN'), ('american', 'AMERICAN'), ('british', 'BRITISH'), ('caribbean', 'CARIBBEAN'), ('chinese', 'CHINESE')], default='chinese', max_length=50)),
                ('ingredients', models.CharField(max_length=1000)),
                ('method', models.CharField(max_length=1000)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
