# Generated by Django 2.2.6 on 2019-10-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_blog', '0002_auto_20191029_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=models.TextField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='method',
            field=models.TextField(blank=True, unique=True),
        ),
    ]
