# Generated by Django 2.2.6 on 2019-10-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_blog', '0003_auto_20191029_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cuisine',
            field=models.CharField(blank=True, choices=[('African', 'AFRICAN'), ('american', 'AMERICAN'), ('british', 'BRITISH'), ('caribbean', 'CARIBBEAN'), ('chinese', 'CHINESE')], default='chinese', max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='default_dinner.jpg', upload_to='media/recipe_pics'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='method',
            field=models.TextField(unique=True),
        ),
    ]
